name: "(T3K) T3000 model perf tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # This cron schedule runs the workflow every 12 hours

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
    secrets: inherit
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
      tracy: true
    secrets: inherit
  t3000-model-perf-tests:
    needs: [build-artifact, build-artifact-profiler]
    secrets: inherit
    uses: ./.github/workflows/t3000-model-perf-tests-impl.yaml
